package org.eclipse.leshan.client.demo;

import org.apache.commons.configuration.ConfigurationException;
import org.apache.commons.configuration.PropertiesConfiguration;
import org.apache.commons.configuration.reloading.FileChangedReloadingStrategy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 
 * @author Autogenerated by Headstart
 * @version 1.0
 *
 */
public class ConfigUtil {

    private static Logger logger = LoggerFactory.getLogger(ConfigUtil.class);

    /**
     * Time (in milliseconds) after which all custom indices are recalculated
     */

    /**
     * sms email configuration keys
     */
    // TODO configUtil for bluewaves

    public static final String CONFIG_PROPS = "config.properties";

    private static PropertiesConfiguration config;

    static {
        try {
            config = new PropertiesConfiguration(CONFIG_PROPS);
            config.setReloadingStrategy(new FileChangedReloadingStrategy());
        } catch (ConfigurationException e) {
            // TODO Auto-generated catch block
            logger.error(e.getMessage());
        }

    }

    public static String getConfigProp(String key) {
        return (String) config.getProperty(key);
    }

    public static void setConfigProp(String key, String value) {
        config.setProperty(key, value);
        try {
            config.save();
        } catch (ConfigurationException e) {
            logger.error("Error Inside  @class :" + ConfigUtil.class.getName() + " @Method :setConfigProp()"
                    + e.getMessage());
        }
    }

    public static Integer parseStringToInt(String key) {
        return Integer.parseInt(getConfigProp(key));

    }

    public static Boolean parseStringToBoolean(String key) {
        return Boolean.parseBoolean(getConfigProp(key));

    }

}
